### ISSUE TITLE
Minimum requirement of iOS for Podfile

### ISSUE THREAD

**Issue by kevinnguy** [Mantle/MTLManagedObjectAdapter#12]
Hi all, I was wondering why the minimum requirement of iOS version for MTLManagedObjectAdapter is iOS 8.0 and Mantle's minimum requirement is iOS 5.0. Is it possible to lower MTLManagedObjectAdapter's minimum requirement? Thanks!

**Comment by dcaunt** [comment]
This is related to https://github.com/Mantle/Mantle/issues/490 – basically the project is using frameworks and therefore requires iOS 8, but the code itself does not require iOS 8. The requirement in the podspec for `MTLManagedObjectAdapter` could probably be lowered but you'll need to contact that podspec maintainer.

**Comment by kevinnguy** [comment]
Thanks @dcaunt , will do!
