### ISSUE TITLE
 'mtl_moa_EXTScope.h' file not found

### ISSUE THREAD

**Issue by engmsaleh** [Mantle/MTLManagedObjectAdapter#13]
Installing using pod and when trying to build the workspace it gives
```
../Pods/MTLManagedObjectAdapter/MTLManagedObjectAdapter/MTLManagedObjectAdapter.m:13:9: 'mtl_moa_EXTScope.h' file not found
```

**Comment by tabuchid** [comment]
I'm also seeing this issue.

**Comment by jspahrsummers** [comment]
We do not maintain the podspec for this project. Please contact the contributors to it.

**Comment by engmsaleh** [comment]
Hi @jspahrsummers , Ok no problem I have found a workaround it seems a naming issue

![screen shot 2015-06-24 at 12 59 16 am](https://cloud.githubusercontent.com/assets/462150/8319228/ff5a01bc-1a14-11e5-94a4-1f4266573bd6.png)
![screen shot 2015-06-24 at 12 59 46 am](https://cloud.githubusercontent.com/assets/462150/8319231/027621c8-1a15-11e5-950d-93c556956250.png)

I have modified the header to 
```
#import "EXTScope.h"
#import "EXTRuntimeExtensions.h"
```

and I have modified the other to
```
		mtl_propertyAttributes *attributes = mtl_copyPropertyAttributes(property);
```

and it worked for now, I will try to contact the maintainer of Podspec to check with.
Thanks for your great effort.

**Comment by MendyK** [comment]
@engmsaleh Does changing that modify the default behavior? If not, can you submit a pull request?

**Comment by engmsaleh** [comment]
@MendyK  No, It doesn't modify the behavior, I have opened issue with the original author as advised , but I think he didn't update it.
What I have done is changing the code itself after installing the pod.
Honestly, I didn't make a Cocoapod before, but I may try :)

**Comment by MendyK** [comment]
@engmsaleh That would be awesome if you could do that :)
