### ISSUE TITLE
Building error on Xcode 6.3

### ISSUE THREAD

**Issue by hankbao** [Mantle/MTLManagedObjectAdapter#8]
Got this error when using carthage to integrate MTLManagedObjectAdapter:

MTLManagedObjectAdapter/MTLManagedObjectAdapter.m:754:41: error: comparison
of array 'attributes->type' not equal to a null pointer is always true

`attributes->type != NULL`

It seems that changing `type` from `char[]` to `char*` can fix this error. So this may actually relate to libextobjc.

**Comment by jspahrsummers** [comment]
This is a legitimate warning/error. A `NULL` comparison is useless because the character array is embedded in the structure allocation itself.

But, ideally, this _would_ be fixed upstream in libextobjc. :wink:

**Comment by hankbao** [comment]
I see. Thanks for your reply.

**Comment by sunkehappy** [comment]
When could this be fixed? I don't like warnings. Thanks.

**Comment by gus-byrnesinnovation** [comment]
+1 is this in the works?

**Comment by need2edit** [comment]
-- Please reply above this line --


Hello Mantle/mtlmanagedobjectadapter,

Thanks for your email - it’s arrived safely in our inbox. We'll get
back to you during our normal business hours, which
are between Monday and Friday from 9am to 6pm EST.

If you’re experiencing an emergency situation, let us know
at emergency@acpdecisions.org [1]. We’ll try to have someone get
back to you as soon as possible.

Thanks and talk to you soon!
The ACP Decisions Team

Links:
------
[1] mailto:emergency@acpdecisions.org

**Comment by jspahrsummers** [comment]
Please do not +1 issues. If you want to see it fixed sooner, please submit a pull request (upstream to libextobjc, as mentioned).

**Comment by need2edit** [comment]
-- Please reply above this line --


Hello Mantle/mtlmanagedobjectadapter,

Thanks for your email - it’s arrived safely in our inbox. We'll get
back to you during our normal business hours, which
are between Monday and Friday from 9am to 6pm EST.

If you’re experiencing an emergency situation, let us know
at emergency@acpdecisions.org [1]. We’ll try to have someone get
back to you as soon as possible.

Thanks and talk to you soon!
The ACP Decisions Team

Links:
------
[1] mailto:emergency@acpdecisions.org

**Comment by grgcombs** [comment]
I believe this is fixed by #23 now.

**Comment by need2edit** [comment]
-- Please reply above this line --


Hello Mantle/mtlmanagedobjectadapter,

Thanks for your email - it’s arrived safely in our inbox. We'll get
back to you during our normal business hours, which
are between Monday and Friday from 9am to 5pm EST.

If you’re experiencing an emergency situation, let us know
at emergency@acpdecisions.org [1]. We’ll try to have someone get
back to you as soon as possible.

Thanks and talk to you soon!
The ACP Decisions Team

Links:
------
[1] mailto:emergency@acpdecisions.org

**Comment by jspahrsummers** [comment]
Yep, thanks!
