### ISSUE TITLE
How to avoid type mismatch problem?

### ISSUE THREAD

**Issue by Vincent-z** [Mantle/MTLManagedObjectAdapter#9]
If i have a NSNumber property, and ths JSON  is NSString.I map to mantle model is ok, but when I convert mantle to NSManagedObject it can't auto check or transform the value, and it crashed. How can i avoid this automatic.

**Comment by jspahrsummers** [comment]
You need to provide a JSON transformer to ensure that the string becomes a number before being assigned to your model object.

See the Mantle [README](https://github.com/Mantle/Mantle/blob/5d864afc4c2786298c2bb94191bca08cd226a737/README.md#mtlmodel).
